### ISSUE TITLE
Criar um link no menu para Contribuição

### ISSUE THREAD

**Issue by lucianobragaweb** [OsProgramadores/op-website-hugo#105]
Uma coisa que notei dificuldade logo de cara foi localizar a maneira como contribuir para o site(me colocando na perspectiva do usuário leigo que não conhece bem GitHub). É realmente muito legal a ideia de sites estáticos que podem ser criados por geradores como o Hugo e hospedados no Github mas acredito que precisamos priorizar esta informação no site, facilitando o acesso para que mais pessoas possam contribuir.

Eu vi o artigo que ensina como contribuir, e sugiro também um vídeo explicando os passos descritos no artigo. Já vou dar um Fork aqui e começar a contribuir. Deixo aqui também meus parabéns pelo projeto.

**Comment by mpinheir** [comment]
Obrigado pela sugestão. Coloquei um link no menu da página principal "Colabore" que direciona o usuário a página onde explicamos como contribuir com o site. Com relação ao vídeo, vamos pensar no caso pois somos todos feios.
