### ISSUE TITLE
Criação de artigo sobre estrutura de dados Fila

### ISSUE THREAD

**Issue by cfguimaraes** [OsProgramadores/op-website-hugo#119]
Só para deixar os camaradas conscientes dos trabalhos em progresso.
Por ser uma boa prática os trabalhos serem discutidos e assim a comunidade saber o andamento do projeto estou criando essa issue para que assim os colegas saibam desse possibilidade.

**Comment by cfguimaraes** [comment]
Sugiro que todos definam workflow's como issues para que possamos dessa forma acompanhar os progressos e até gerenciarmos melhor os branches locais.
Vou trabalhar nessa estória na semana corrente de 17/set.

**Comment by cfguimaraes** [comment]
Visto que o artigo sobre pilhas foi aceito, vou começar a trabalhar nesse artigo então.

**Comment by marcopaganini** [comment]
Ping?

**Comment by mpinheir** [comment]
Acho que o @cfguimaraes se desinteressou em tocar o artigo a frente.

**Comment by marcopaganini** [comment]
Fechado por inatividade.
