### ISSUE TITLE
Erro ao tentar rodar o comando: hugo -wv

### ISSUE THREAD

**Issue by carloshenriqueribeiro** [OsProgramadores/op-website-hugo#277]
![error](https://user-images.githubusercontent.com/19979749/51444776-355dbb80-1ce3-11e9-931a-288fb5354b9d.JPG)

**Comment by marcopaganini** [comment]
Talvez voce tenha esquecido da opção "--recursive" quando fez o git clone?

**Comment by carloshenriqueribeiro** [comment]
@marcopaganini foi isso mesmo.

para quem esquecer, basta rodar este comando.

`git submodule update --init --recursive`
