### ISSUE TITLE
Correções

### ISSUE THREAD

**Issue by david81brs** [OsProgramadores/op-website-hugo#31]
Verificar se as palavras em língua estrangeira ficam em itálico por todas as páginas.

Site não parece está com ajuste de LOCALE.

Quem somos: "programaç**ã**o", "Não h**á** exigências", "pr**é**-requisitos"; hífen em bem-vindo. 

Quem somos: "O nosso grupo é formado por pessoas de todas as idades e níveis de experiência. Nosso objetivo é disseminar o conhecimento de **programação** e assuntos ligados aos computadores em geral, além de formar um grupo onde todas as opiniões e perguntas sejam **bem-vindas**. Não **há** exigências ou **pré-**requisitos. Sua presença será sempre **bem-vinda**!"

Bernardino Campos: "Eletrônico de formação; Rádio Amador por **_hobby_**; (...) Ultimamente tem se envolvido bastante com programação de sistemas embarcados. Totalmente **_Geek_**.

_Post_ _Hacking_:  ideia (novo acordo ortográfico). Pedimos **aos** (aqueles).

**Comment by mpinheir** [comment]
@david81brs verifique por favor se todos os problemas foram resolvidos com o pull request que você envio e,  caso tudo esteja bem, feche por favor o issue para marcar como resolvido. Obrigado!

**Comment by david81brs** [comment]
@mpinheir Acho que falta a avaliação dos dois primeiros itens. 

1. Palavras estrangeiras em _itálico_;
2. Locale do Site https://gohugo.io/tutorials/create-a-multilingual-site/
e também outras correções:
rodapé: O nosso grupo não tem fins lucrativos. O nosso objetivo é disseminar conhecimento em várias áreas da ciência da computação **(ponto)**.
Post Hacking: ideia (novo acordo ortográfico).

**Comment by mpinheir** [comment]
@david81brs Ajuda com estas correções por favor. Faz o teste na tua máquina usando o localhost e depois envia as modificações propostas usando o Pull Request. Assim reduzimos a carga de trabalho de todos. Obrigado pela ajuda!

**Comment by marcopaganini** [comment]
Fechado como obsoleto.
