### ISSUE TITLE
Migrar gráficos de performance das soluções e arquivos de teste do do Desafio 5 para o site do grupo

### ISSUE THREAD

**Issue by mpinheir** [OsProgramadores/op-website-hugo#310]
Os gráficos de performance das soluções do desafio 5 estão gentilmente hospedados em: https://www.bcampos.com/Graphs.php e precisamos migrar os gráficos e os arquivos de teste par o site do grupo.

**Comment by marcopaganini** [comment]
Algum voluntário? :)

**Comment by DevAspirerKlaus** [comment]
Até me voluntariava, mas ainda tô enrolado com o Hugo no meu PC. Tô com o
arquivo pronto a mais de uma semana, mas não posso upar porque não tem como
testar.
