### ISSUE TITLE
Testar links listados no osprogramadores e remover itens obsoletos

### ISSUE THREAD

**Issue by mpinheir** [OsProgramadores/op-website-hugo#369]
Seria ótimo se alguém pudesse testar a sessão de [links](https://osprogramadores.com/links/) do [osprogramadores.com](https://osprogramadores.com) para verificar se os links funcionam ok e remover o que não está funcionando ou atualizar o que precisa ser atualizado.

**Comment by rixgrady** [comment]
Então... tds os links estão funcionando mas na pagina inicial em "artigos recentes" possui 3 links, um na imagem outro no titulo e outro no final do texto, então, tirar o link do titulo seria algo sábio a se fazer

**Comment by mpinheir** [comment]
Beleza. Fique a vontade de mandar o PR para o que você acha que precisa ser consertado. Precisamos de toda a ajuda que puder nos dar.

**Comment by Cadesh** [comment]
Olá, eu fiz um script em Python que busca recursivamente todos os links na página e arquivos internos (html, yaml). O programa testa  e gera um relatório com o resultado dos links quebrados. Não é mais necessário testar manualmente.  Fiz um PR para adicionar o script.
