### ISSUE TITLE
Criar um artigo sobre Filas.

### ISSUE THREAD

**Issue by mpinheir** [OsProgramadores/op-website-hugo#373]
Entender bem estrutura de dados e algoritmos é algo de extrema importância para o desenvolvimento de programas. Seria ótimo adicionar um artigo sobre Filas ao site.

**Comment by mayconb2** [comment]
Gostaria de contribuir com este!

**Comment by mpinheir** [comment]
@mayconb2 como o @marcopaganini explicou em outro post, você precisa clonar o projeto do site e submeter o PR com o teu artigo para avaliação. As instruções sobre como contribuir para o site estão em: [https://github.com/OsProgramadores/op-website-hugo/blob/master/CONTRIBUTING.md](https://github.com/OsProgramadores/op-website-hugo/blob/master/CONTRIBUTING.md)
