### ISSUE TITLE
Criar artigo sobre como configurar um computador com Linux para desenvolvimento.

### ISSUE THREAD

**Issue by mpinheir** [OsProgramadores/op-website-hugo#376]
Que tal criar um artigo sobre como configurar um computador com Linux para o desenvolvimento de aplicações em geral. O artigo poderia falar sobre preparar um ambiente de desenvolvimento e testes para aplicações desktop, web e mobile. Talvez isso possa gerar múltiplos artigos ao invés de apenas 1.

**Comment by leandroramos** [comment]
Eu escrevi alguns artigos sobre instalação de ambiente LAMP e algo sobre Docker, mas em sistemas diferentes, como Debian, Fedora e Void Linux. Estou pensando numa forma de fazer um artigo para todos ou se faço assim separado mesmo.
