### ISSUE TITLE
Criar artigo sobre como configurar um computador com Windows para desenvolvimento.

### ISSUE THREAD

**Issue by mpinheir** [OsProgramadores/op-website-hugo#377]
A ideia seria criar um artigo, voltado a usuários do Sistema Operacional Windows, orientando sobre as ferramentas básicas a serem instaladas para se montar um ambiente de desenvolvimento e testes de aplicações.

**Comment by lucaskds** [comment]
@mpinheir atualmente estou montando um artigo pra configuração de um ambiente de desenvolvimento utilizando o WSL2 (Windows Subsystem for Linux) no Windows 10... Acha que se encaixa nesse contexto ou melhor criar a parte? Já que não é nem 100% Linux e nem 100% Windows 😅

**Comment by mpinheir** [comment]
Acho que é valido. Monta o artigo e manda o PR para submeter para o site.

**Comment by isaacmsl** [comment]
Posso trabalhar nesse artigo?
