### ISSUE TITLE
Criar um artigo sobre como montar um curriculum para ajudar na busca de estágio ou emprego

### ISSUE THREAD

**Issue by mpinheir** [OsProgramadores/op-website-hugo#378]
Muitos dos participantes do grupo estão iniciando nas suas carreiras e seria interessante criar um artigo explicando a melhor forma de montar um curriculum.

**Comment by mayconb2** [comment]
Olá @mpinheir ! Gostaria de ajudar nesta issue. Como posso proceder?

**Comment by marcopaganini** [comment]
@mayconb2 Toda ajuda é bem vinda. :) Normalmente, os artigos vão no diretório "blog". Voce tem que fazer o clone do repositório (não se esqueça do --recursive) e criar um ar um arquivo markdown no diretório "content/blog" (digamos curriculum.md, ou algo assim). Observe o formato nos outros arquivos, pois os arquivos precisam de um cabeçalho para renderizar corretamente.
