### ISSUE TITLE
Simplificar o acesso ao grupo do Telegram a partir do osprogramadores.com.

### ISSUE THREAD

**Issue by mpinheir** [OsProgramadores/op-website-hugo#382]
O único elo de ligação entre o site e o grupo do telegram [https://t.me/osprogramadores](https://t.me/osprogramadores) é o link associado ao texto "Junte-se a nós no Telegram". Precisamos melhorar a visibilidade deste link pois muitos visitantes sequer devem ver que há a possibilidade de se juntar ao grupo no Telegram.

**Comment by BiancaPereira** [comment]
Oii, posso adicionar o link. Pensei que no rodapé poderia ser um bom lugar, já que aparece em todas as páginas. O que acha?

**Comment by mpinheir** [comment]
Acho uma ideia interessante. Manda um PR @BiancaPereira

**Comment by isaacmsl** [comment]
Olá, @mpinheir . O projeto ainda está com essa necessidade?

**Comment by mpinheir** [comment]
@isaacmsl O que você tem em mente?

**Comment by isaacmsl** [comment]
Acredito que deve ser colocado um button "Call to action" (CTA). Exemplo
![ideia](https://user-images.githubusercontent.com/31693006/137212585-ef300432-0c51-4ed4-a469-a018beca5ab7.png)

**Comment by mpinheir** [comment]
Achei a ideia interrrance para acho que o Highscores fica melhor associado como um sub-menu dos desafios e o botão de comunidade no canto direito fica meio redundante por que já temos o "Junte-se a nós no Telegram" bem no meio da tela. Talvez transformar o "Junte-se a nós no Telegram" em um botão azul para chamar atenção seria melhor? O que acha?

**Comment by isaacmsl** [comment]
Concordo com o Highscores no submenu dos desafios. Com relação ao button no menu, é importante lembrar que o intuito é que em todas as páginas sempre a opção entrar no grupo do Telegram aparecerá. Por fim, para resolver a possível redundância, pode ser feita uma condição para só mostrar o button no menu se a página atual for diferente da `/index`.
