### ISSUE TITLE
Adicionar o https://t.me/osprogramadores a lista de links de grupos do Telegram.

### ISSUE THREAD

**Issue by mpinheir** [OsProgramadores/op-website-hugo#384]
Acabei de perceber que não incluímos o [https://t.me/osprogramadores](https://t.me/osprogramadores) na lista de grupos do Telegram que temos em [https://osprogramadores.com/links/](https://osprogramadores.com/links/)

**Comment by gionaufal** [comment]
Eu ia incluir esse link, mas percebi que ele existe sim na página que você indicou, e está funcionando :)

**Comment by mpinheir** [comment]
Obrigado, mova então o link para o osprogramadores para uma posição de destaque acima da lista de grupos pois afinal e’ o grupo do nosso site. Obrigado por ajudar.
