### ISSUE TITLE
Link para possível grupo de Telegram descontinuado

### ISSUE THREAD

**Issue by bpires** [OsProgramadores/op-website-hugo#700]
Na página de links, existe um link para o grupo de Telegram chamado JavaScript Brasil:

![image](https://user-images.githubusercontent.com/86871991/169712185-5a5281cb-f7b7-43eb-acc9-955196b6a2c1.png)

Contudo, ao entrar, notei que, embora o grupo possua 713 membros, tem pouquíssimas e antigas mensagens, sem nenhum conteúdo técnico, não possui descrição e, o que chama a atenção, é que a pinned message é um GIF obsceno.

![image](https://user-images.githubusercontent.com/86871991/169712380-110f7b7e-79f7-44f0-930f-a20ec6cd1776.png)

Não sei o que houve com o grupo, porém acredito que não deva permanecer na lista de links do OsProgramadores.

**Comment by marcopaganini** [comment]
https://github.com/OsProgramadores/op-website-hugo/pull/701 remove o grupo
da lista.
