### ISSUE TITLE
Duvida sobre um comando "hugo -wv" abordado no site na parte de "Como contribuir".

### ISSUE THREAD

**Issue by ValdineiJunior** [OsProgramadores/op-website-hugo#790]
Quando fiz minha primeira contribuição ao site, percebi que nessa parte explicativa, com o título "Modificando o conteúdo e fazendo o preview".

"3.Digite hugo -wv seguido de ENTER. Os arquivos HTML serão gerados no diretório public."

Esse comando "hugo -wv" não gera o conteúdo em http://localhost:1313/

Ao invés disso utilizei "hugo server". Que gerou corretamente o conteúdo.

Gostaria de saber se é só no meu caso, ou se fiz algo de errado. 

Pra caso necessario corrigir o comando no site.

**Comment by lgrando1** [comment]
Compartilho de tal situação. Tive que utilizar o "Hugo server"

**Comment by mpinheir** [comment]
@ValdineiJunior  e @lgrando1 testei aqui e os sintomas foram o mesmo. Acho que o `hugo -wv` era em uma versão mais antiga do Hugo mas não lembro. Podem por favor enviar o PR para trocar o `hugo -wv` para `hugo server`? Acho que vai ficar mais simples para todos assim. Obrigado!
