### ISSUE TITLE
Sugestão - Critérios de qualidade de postagem

### ISSUE THREAD

**Issue by lgrando1** [OsProgramadores/op-website-hugo#792]
Gostaria de sugerir a inclusão de critérios de qualidade para futuras postagens em https://github.com/OsProgramadores/op-website-hugo#como-contribuir com o intuito de evitar retrabalhos.

Algumas sugestões de critérios:
1. Como ordenar os links (na aba Links);
2. Verificar se os itens são repetidos (ex: onde verificar);
3. O que é esperado em uma contribuição (um exemplo). 
etc...

Muito obrigado e parabéns pela iniciativa.

**Comment by mpinheir** [comment]
@lgrando1 Gostei. Manda um screenshot para mim mostrando onde vocÊ quer colocar os detalhes e eu aprovando você manda o PR com a mod em seguida

**Comment by lgrando1** [comment]
@mpinheir segue sugestão, fiz localmente em meu repositório. Caso aprovado, seria também interessante ouvir de vocês moderadores, os principais itens de revisão mais solicitados.  
![sugest](https://user-images.githubusercontent.com/36816722/209450623-a20e84da-6147-461b-ac24-817cd83da844.png)

**Comment by mpinheir** [comment]
@lgrando1 Gostei. Obrigado. A minha única sugestão seria tirar o item 3 pois a maioria dos nossos visitantes são do Brasil e o site é padrão pt.br. Não faria sentido trocar tela por ecran ou arquivo por ficheiro. No mais é só enviar o PR por favor. Obrigado.

**Comment by lgrando1** [comment]
@mpinheir PR feita. Sua sugestão faz sentido, muito obrigado!. Aproveitei para arrumar o ultimo link (aquele do grupo do telegram), estava com um link apontando para o site do HUGO, por favor veja se está correto. Muito obrigado sucesso!

**Comment by lgrando1** [comment]
@mpinheir posso fazer uma sugestão aqui: https://osprogramadores.com/blog/2019/03/12/por-onde-comecar/

Pensei em incluir um passo 0, ou seja, sugerir que novos usuários conhecessem uma linguagem baseada em blocos (Exemplo: MIT Scratch ou o APP Inventor), utilizar jogos (como o RPG do Freecodecamp, o Glasshopper da Google para JS) para treinar logica, o uso do Khan Academy  para conceitos diversos (inclusive computação), o Duolingo para aprender idiomas. Se achar legal faço um rascunho. Obrigado.

**Comment by mpinheir** [comment]
@lgrando1 Eu receio que isso meramente iria confundir a acabeça das pessoas. Este por onde começar é simples e direto ao ponto e atende seu propósito. Agradeço a sugestão mas não será aprovada.

**Comment by lgrando1** [comment]
@mpinheir ah entendi, sim sim, faz todo sentido. obrigado por avaliar a ideia.
