### ISSUE TITLE
Fork do repositório?

### ISSUE THREAD

**Issue by disouzam** [OsProgramadores/op-website-hugo#926]
Fui notificado de uma menção no commit indicado abaixo. 

https://github.com/0xJEth/op-website-hugo/commit/a81c45c70c88defd5380604d10e9ff1c8025120b

Vejam os commits - foram reescritos:

![image](https://github.com/user-attachments/assets/67582f0e-6c76-4e0f-a793-923a93ff2800)

Vocês tem ciência do que se trata esse repo do usuário 0xJEth?

**Comment by magnussolidus** [comment]
Não tenho ciência de quem seja ou do que se trata. Me parece ser uma conta que usa bot para fazer commits e clonar repositórios. Eu reportei o usuário, sugiro que faça o mesmo.

**Comment by disouzam** [comment]
Já reportei na semana passada.
